"""Write the dealt papers out as SQL, CSV and a human review page.

Nothing here talks to the database. Loading 600 questions into a live product
should be a deliberate act by a person who has read them, so the agent's last
step is to hand over a file — not to write to production itself.
"""

from __future__ import annotations

import csv
import html
import json
import os


def _sql_str(value) -> str:
    if value is None:
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


def to_sql(dealt: dict[str, list[dict]], papers: list, course, path: str) -> None:
    by_id = {p.id: p for p in papers}
    total = sum(len(v) for v in dealt.values())

    with open(path, "w") as fh:
        fh.write(f"-- {course.title}\n")
        fh.write(f"-- {total} questions across {len(dealt)} papers, "
                 f"generated by tools/mcq-agent.\n")
        fh.write("--\n")
        fh.write("-- Review the questions before running this. Once loaded, mark the\n")
        fh.write("-- course live:  update public.courses set is_live = true where id = "
                 f"{_sql_str(course.id)};\n")
        fh.write("--\n")
        fh.write("-- Re-runnable: the delete below clears any previous load for these\n")
        fh.write("-- papers so a second run does not double the question bank.\n\n")
        fh.write("begin;\n\n")

        ids = ", ".join(_sql_str(pid) for pid in dealt)
        fh.write(f"delete from public.questions where quiz_id in ({ids});\n\n")

        for pid, items in sorted(dealt.items(), key=lambda kv: by_id[kv[0]].exam_order):
            paper = by_id[pid]
            fh.write(f"-- {paper.title} ({len(items)} questions)\n")
            fh.write("insert into public.questions "
                     "(quiz_id, question_no, question_text, option_a, option_b, "
                     "option_c, option_d, correct_option, explanation) values\n")
            rows = []
            for n, item in enumerate(items, 1):
                o = item["options"]
                rows.append(
                    f"  ({_sql_str(pid)}, {n}, {_sql_str(item['question'])}, "
                    f"{_sql_str(o[0])}, {_sql_str(o[1])}, {_sql_str(o[2])}, "
                    f"{_sql_str(o[3])}, {_sql_str(item['correct'])}, "
                    f"{_sql_str(item['explanation'])})"
                )
            fh.write(",\n".join(rows) + ";\n\n")

        fh.write("commit;\n")


def to_csv(dealt: dict[str, list[dict]], papers: list, path: str) -> None:
    by_id = {p.id: p for p in papers}
    with open(path, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["paper", "quiz_id", "question_no", "question_text",
                    "option_a", "option_b", "option_c", "option_d",
                    "correct_option", "explanation", "chapter", "pages", "chunk_id"])
        for pid, items in sorted(dealt.items(), key=lambda kv: by_id[kv[0]].exam_order):
            paper = by_id[pid]
            for n, item in enumerate(items, 1):
                o = item["options"]
                w.writerow([paper.title, pid, n, item["question"], o[0], o[1], o[2], o[3],
                            item["correct"], item["explanation"],
                            f"{item.get('chapter_no')} {item.get('chapter_title', '')}",
                            f"{item.get('page_start')}-{item.get('page_end')}",
                            item.get("chunk_id", "")])


def to_review_html(dealt: dict[str, list[dict]], papers: list, course, path: str) -> None:
    """A page a human can actually read before approving 600 questions."""
    by_id = {p.id: p for p in papers}
    esc = html.escape

    parts = [
        "<meta charset='utf-8'><title>Review — %s</title>" % esc(course.title),
        "<meta name='viewport' content='width=device-width,initial-scale=1'>",
        """<style>
        :root{--fg:#0f2b21;--bg:#fff;--mut:#5b6b64;--line:#e2e8f0;--ok:#059669}
        @media(prefers-color-scheme:dark){:root{--fg:#e6f2ec;--bg:#0d1512;--mut:#9fb3aa;--line:#22322c}}
        body{margin:0;padding:24px;font:15px/1.55 system-ui,sans-serif;color:var(--fg);background:var(--bg)}
        .wrap{max-width:880px;margin:0 auto}
        h1{font-size:1.5rem;margin:0 0 4px} h2{font-size:1.1rem;margin:32px 0 10px}
        .sub{color:var(--mut);margin:0 0 20px}
        .q{border:1px solid var(--line);border-radius:12px;padding:14px 16px;margin:0 0 10px}
        .stem{font-weight:600;margin:0 0 8px}
        ol{margin:0;padding-left:22px} li{margin:2px 0}
        li.right{color:var(--ok);font-weight:600}
        .why{color:var(--mut);font-size:.9rem;margin:8px 0 0}
        .src{color:var(--mut);font-size:.78rem;margin:6px 0 0}
        </style>""",
        "<div class='wrap'>",
        f"<h1>{esc(course.title)}</h1>",
        f"<p class='sub'>{sum(len(v) for v in dealt.values())} questions · "
        f"correct answer in green · source chapter and page under each question.</p>",
    ]

    for pid, items in sorted(dealt.items(), key=lambda kv: by_id[kv[0]].exam_order):
        paper = by_id[pid]
        parts.append(f"<h2>{esc(paper.title)} — {len(items)} questions</h2>")
        for n, item in enumerate(items, 1):
            right = "ABCD".index(item["correct"])
            opts = "".join(
                f"<li class='{'right' if i == right else ''}'>{esc(o)}</li>"
                for i, o in enumerate(item["options"])
            )
            parts.append(
                f"<div class='q'><p class='stem'>{n}. {esc(item['question'])}</p>"
                f"<ol type='A'>{opts}</ol>"
                f"<p class='why'>{esc(item['explanation'])}</p>"
                f"<p class='src'>Chapter {item.get('chapter_no')} "
                f"{esc(str(item.get('chapter_title', '')).title())} · "
                f"pages {item.get('page_start')}–{item.get('page_end')}</p></div>"
            )

    parts.append("</div>")
    with open(path, "w") as fh:
        fh.write("\n".join(parts))


def write_all(dealt, papers, course, out_dir: str) -> dict[str, str]:
    os.makedirs(out_dir, exist_ok=True)
    paths = {
        "sql": os.path.join(out_dir, f"questions_{course.slug}.sql"),
        "csv": os.path.join(out_dir, f"questions_{course.slug}.csv"),
        "html": os.path.join(out_dir, f"review_{course.slug}.html"),
        "json": os.path.join(out_dir, f"papers_{course.slug}.json"),
    }
    to_sql(dealt, papers, course, paths["sql"])
    to_csv(dealt, papers, paths["csv"])
    to_review_html(dealt, papers, course, paths["html"])
    with open(paths["json"], "w") as fh:
        json.dump(dealt, fh, indent=1)
    return paths
